test checkout of file lacking trailing \n over pserver protocol
This test reproduces the bug fixed in
commit d3b3344bc26d90acb081fe827aed60257d931cfe where our custom cvs
client would fail to check out a file which lacks a trailing newline
from a remote CVS server.

The error triggered by the test without the fix in place is:

CVSProtocolError: Overlong response from CVS server:
b'delta with no trailing eolok\n'